### ISSUE TITLE
Input not recognized

### ISSUE THREAD

**Issue by MaFeLP** [lxgr-linux/scrap_engine#1]
When playing `multi` with two persons and two keys are pressed at the same time, some might not get recognized and their commands are not executed.

**Comment by lxgr-linux** [comment]
This should be fixed by now, because I switched from an input variable to an input array.
Please verify this.

**Comment by MaFeLP** [comment]
Works when users press at the exact same time, but when pressing directly after one another not.

**Comment by lxgr-linux** [comment]
This may fix the issue.
