### ISSUE TITLE
Using Chinese will cause the frame to shift

### ISSUE THREAD

**Issue by yhy666888** [lxgr-linux/scrap_engine#16]
![image](https://user-images.githubusercontent.com/45033094/160805536-ac97f590-8ec4-4052-bccf-a08da24f1cab.png)
Using Chinese characters will become like this. Is there any way to solve it?

**Comment by lxgr-linux** [comment]
That may be because those characters take up more space than a standard character in monospace fonts, I will look into this and come up with a solution.

**Comment by lxgr-linux** [comment]
You can place a `\u200b` behind all of your Chinese character, that's a zero-space character and will make python think the has actually the length it takes on the screen.

**Comment by yhy666888** [comment]
Thanks for your help.But it doesn't seem to work.
![image](https://user-images.githubusercontent.com/45033094/160963886-0a396c37-ebb3-4886-8e78-a71b62ffbd6b.png)

![image](https://user-images.githubusercontent.com/45033094/160962275-cd462e48-bd2a-41bd-b61f-b3d1f9550074.png)

**Comment by lxgr-linux** [comment]
This will work:
```python
s = se.Square(height=10, width=12, char="風")
for i, obj in enumerate(s.obs):
     if i%2 == 0:
             obj.rechar("")
```

It creates a square that's double the size of yours, but then strips out every second character to get to the desired size.

**Comment by yhy666888** [comment]
That's a good idea. I'll give it a try.
