### ISSUE TITLE
Terminal resizing is broken

### ISSUE THREAD

**Issue by ttpf-P** [lxgr-linux/scrap_engine#8]
Resizing scrap_test.py/ scrap_bench.py didn't resize map

**Comment by ttpf-P** [comment]
tested on win 10 on live build (https://github.com/lxgr-linux/scrap_engine/commit/cc4bbc002c16c93e94c980a4d2a6a586b4648dc0)
as well as version 0.3.3

**Comment by lxgr-linux** [comment]
It's not broken, it's not implemented.

**Comment by ttpf-P** [comment]
oh, thought i had seen it running once
